### ISSUE TITLE
Flask middleware breaking

### ISSUE THREAD

**Issue by robfromboulder** [resurfaceio/logger-python#48]
Seeing this error with the test-flask app:

```
robfromboulder@radware3 test-flask % make ping
curl http://localhost/ping
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>
robfromboulder@radware3 test-flask % make logs
[2021-04-21 03:59:38 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-04-21 03:59:38 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2021-04-21 03:59:38 +0000] [1] [INFO] Using worker: sync
[2021-04-21 03:59:38 +0000] [9] [INFO] Booting worker with pid: 9
[2021-04-21 03:59:50 +0000] [9] [ERROR] Error handling request /ping
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/usagelogger/flask.py", line 58, in __call__
    body__ = self.request_body(environ)
  File "/usr/local/lib/python3.7/site-packages/usagelogger/flask.py", line 54, in request_body
    return body.decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'
q^Cmake: *** [logs] Error 255
```

**Comment by robfromboulder** [comment]
Tests now pass, thanks!
